name: edm
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy>=1.24
  - scipy>=1.10
  - pillow>=9
  - click>=8.1
  - psutil
  - requests
  - tqdm
  - imageio
  - pyyaml
  - pytorch>=2.1
  - torchvision
  - pip:
      - imageio-ffmpeg>=0.4.3
      - pyspng
      - omegaconf
      - gdown
      - lightning
      - git+https://github.com/openai/CLIP.git
      - transformers>=4.41.2
      - taming-transformers
      - git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
      - kornia
      - fairscale
      - piq
      - accelerate>=0.31.0
      - huggingface-hub>=0.34.0,<2.0
      - safetensors>=0.3.1
      - sentencepiece>=0.1.91,!=0.1.92
      - protobuf>=3.20.3,<4
      - ftfy
      - invisible-watermark>=0.2.0
      - timm
