run:
  output_root: "exps"
  run_name: "sd3_smoke"
  seed: 0

data:
  predictor_snapshot: "exps/99999-ms_coco-11-20-epd-dpm-1-discrete/network-snapshot-099999.pkl"
  prompt_csv: null  # reuse MS-COCO prompts; adjust if you have custom prompt files

model:
  dataset_name: "ms_coco"
  guidance_type: "cfg"
  guidance_rate: 7.5
  schedule_type: "flowmatch"
  schedule_rho: 1.0
  num_steps: null
  num_points: null
  backend: "sd3"
  sigma_min: 1.0e-3
  sigma_max: 1.0
  backend_options:
    model_name_or_path: "stabilityai/stable-diffusion-3-medium-diffusers"
    torch_dtype: "auto"
    enable_model_cpu_offload: false

reward:
  weights_path: "weights/HPS_v2.1_compressed.pt"
  batch_size: 2
  enable_amp: true
  cache_dir: "weights"

ppo:
  rollout_batch_size: 8
  rloo_k: 4
  ppo_epochs: 1
  minibatch_size: 4
  learning_rate: 5.0e-5
  clip_range: 0.2
  kl_coef: 0.0
  entropy_coef: 0.0
  max_grad_norm: 1.0
  decode_rgb: true
  steps: 1
  dirichlet_concentration: 150.0

logging:
  log_interval: 1
  save_interval: 50
